//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgIO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class gStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal gStr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgIO.gStr", typeof(gStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/farmerbriantee/AgOpenGPS/wiki/03.-AgIO-Orientation.
        /// </summary>
        internal static string gsAgIOHelp {
            get {
                return ResourceManager.GetString("gsAgIOHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authourizing.
        /// </summary>
        internal static string gsAuthourizing {
            get {
                return ResourceManager.GetString("gsAuthourizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/farmerbriantee/AgOpenGPS/wiki/05.-Ethernet-Setup.
        /// </summary>
        internal static string gsEthernetHelp {
            get {
                return ResourceManager.GetString("gsEthernetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening.
        /// </summary>
        internal static string gsListening {
            get {
                return ResourceManager.GetString("gsListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTRIP.
        /// </summary>
        internal static string gsNTRIP {
            get {
                return ResourceManager.GetString("gsNTRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/farmerbriantee/AgOpenGPS/wiki/04.-RTK-Setup.
        /// </summary>
        internal static string gsNTRIP_Help {
            get {
                return ResourceManager.GetString("gsNTRIP_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Return.
        /// </summary>
        internal static string gsSaveAndReturn {
            get {
                return ResourceManager.GetString("gsSaveAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Comms.
        /// </summary>
        internal static string gsSaveComms {
            get {
                return ResourceManager.GetString("gsSaveComms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/farmerbriantee/AgOpenGPS/wiki/06.-Serial-Monitor.
        /// </summary>
        internal static string gsSerialMonHelp {
            get {
                return ResourceManager.GetString("gsSerialMonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string gsWaiting {
            get {
                return ResourceManager.GetString("gsWaiting", resourceCulture);
            }
        }
    }
}
