//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgOpenGPS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-15")]
        public double setCam_pitch {
            get {
                return ((double)(this["setCam_pitch"]));
            }
            set {
                this["setCam_pitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM GPS...")]
        public string setPort_portNameGPS {
            get {
                return ((string)(this["setPort_portNameGPS"]));
            }
            set {
                this["setPort_portNameGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4800")]
        public int setPort_baudRate {
            get {
                return ((int)(this["setPort_baudRate"]));
            }
            set {
                this["setPort_baudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double setVehicle_toolWidth {
            get {
                return ((double)(this["setVehicle_toolWidth"]));
            }
            set {
                this["setVehicle_toolWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double setVehicle_toolOverlap {
            get {
                return ((double)(this["setVehicle_toolOverlap"]));
            }
            set {
                this["setVehicle_toolOverlap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2")]
        public double setVehicle_toolTrailingHitchLength {
            get {
                return ((double)(this["setVehicle_toolTrailingHitchLength"]));
            }
            set {
                this["setVehicle_toolTrailingHitchLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30")]
        public global::System.Drawing.Point setWindow_Location {
            get {
                return ((global::System.Drawing.Point)(this["setWindow_Location"]));
            }
            set {
                this["setWindow_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900, 600")]
        public global::System.Drawing.Size setWindow_Size {
            get {
                return ((global::System.Drawing.Size)(this["setWindow_Size"]));
            }
            set {
                this["setWindow_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWindow_Maximized {
            get {
                return ((bool)(this["setWindow_Maximized"]));
            }
            set {
                this["setWindow_Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWindow_Minimized {
            get {
                return ((bool)(this["setWindow_Minimized"]));
            }
            set {
                this["setWindow_Minimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int setVehicle_numSections {
            get {
                return ((int)(this["setVehicle_numSections"]));
            }
            set {
                this["setVehicle_numSections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-8.0")]
        public decimal setSection_position1 {
            get {
                return ((decimal)(this["setSection_position1"]));
            }
            set {
                this["setSection_position1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3.0")]
        public decimal setSection_position2 {
            get {
                return ((decimal)(this["setSection_position2"]));
            }
            set {
                this["setSection_position2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.0")]
        public decimal setSection_position3 {
            get {
                return ((decimal)(this["setSection_position3"]));
            }
            set {
                this["setSection_position3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8.0")]
        public decimal setSection_position4 {
            get {
                return ((decimal)(this["setSection_position4"]));
            }
            set {
                this["setSection_position4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setSection_position5 {
            get {
                return ((decimal)(this["setSection_position5"]));
            }
            set {
                this["setSection_position5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setSection_position6 {
            get {
                return ((decimal)(this["setSection_position6"]));
            }
            set {
                this["setSection_position6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double setVehicle_antennaHeight {
            get {
                return ((double)(this["setVehicle_antennaHeight"]));
            }
            set {
                this["setVehicle_antennaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double setVehicle_lookAhead {
            get {
                return ((double)(this["setVehicle_lookAhead"]));
            }
            set {
                this["setVehicle_lookAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM Section...")]
        public string setPort_portNameRelay {
            get {
                return ((string)(this["setPort_portNameRelay"]));
            }
            set {
                this["setPort_portNameRelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasRelayConnected {
            get {
                return ((bool)(this["setPort_wasRelayConnected"]));
            }
            set {
                this["setPort_wasRelayConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setVehicle_isToolTrailing {
            get {
                return ((bool)(this["setVehicle_isToolTrailing"]));
            }
            set {
                this["setVehicle_isToolTrailing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setVehicle_toolOffset {
            get {
                return ((double)(this["setVehicle_toolOffset"]));
            }
            set {
                this["setVehicle_toolOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setVehicle_isToolBehindPivot {
            get {
                return ((bool)(this["setVehicle_isToolBehindPivot"]));
            }
            set {
                this["setVehicle_isToolBehindPivot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1")]
        public double setVehicle_antennaPivot {
            get {
                return ((double)(this["setVehicle_antennaPivot"]));
            }
            set {
                this["setVehicle_antennaPivot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double setVehicle_wheelbase {
            get {
                return ((double)(this["setVehicle_wheelbase"]));
            }
            set {
                this["setVehicle_wheelbase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.5")]
        public double setVehicle_hitchLength {
            get {
                return ((double)(this["setVehicle_hitchLength"]));
            }
            set {
                this["setVehicle_hitchLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int setDisplay_delayFixPrev {
            get {
                return ((int)(this["setDisplay_delayFixPrev"]));
            }
            set {
                this["setDisplay_delayFixPrev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int setDisplay_delayCameraPrev {
            get {
                return ((int)(this["setDisplay_delayCameraPrev"]));
            }
            set {
                this["setDisplay_delayCameraPrev"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setVehicle_turnOffDelay {
            get {
                return ((double)(this["setVehicle_turnOffDelay"]));
            }
            set {
                this["setVehicle_turnOffDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setVehicle_isPivotBehindAntenna {
            get {
                return ((bool)(this["setVehicle_isPivotBehindAntenna"]));
            }
            set {
                this["setVehicle_isPivotBehindAntenna"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setVehicle_isSteerAxleAhead {
            get {
                return ((bool)(this["setVehicle_isSteerAxleAhead"]));
            }
            set {
                this["setVehicle_isSteerAxleAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setCam_isAtanCam {
            get {
                return ((bool)(this["setCam_isAtanCam"]));
            }
            set {
                this["setCam_isAtanCam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setDisplay_triangleResolution {
            get {
                return ((double)(this["setDisplay_triangleResolution"]));
            }
            set {
                this["setDisplay_triangleResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setIsMetric {
            get {
                return ((bool)(this["setIsMetric"]));
            }
            set {
                this["setIsMetric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setIsGridOn {
            get {
                return ((bool)(this["setIsGridOn"]));
            }
            set {
                this["setIsGridOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setIsLightbarOn {
            get {
                return ((bool)(this["setIsLightbarOn"]));
            }
            set {
                this["setIsLightbarOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setIsAreaRight {
            get {
                return ((bool)(this["setIsAreaRight"]));
            }
            set {
                this["setIsAreaRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setCurrentDir {
            get {
                return ((string)(this["setCurrentDir"]));
            }
            set {
                this["setCurrentDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public byte setFieldColorR {
            get {
                return ((byte)(this["setFieldColorR"]));
            }
            set {
                this["setFieldColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public byte setFieldColorG {
            get {
                return ((byte)(this["setFieldColorG"]));
            }
            set {
                this["setFieldColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public byte setFieldColorB {
            get {
                return ((byte)(this["setFieldColorB"]));
            }
            set {
                this["setFieldColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public byte setSectionColorR {
            get {
                return ((byte)(this["setSectionColorR"]));
            }
            set {
                this["setSectionColorR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190")]
        public byte setSectionColorG {
            get {
                return ((byte)(this["setSectionColorG"]));
            }
            set {
                this["setSectionColorG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public byte setSectionColorB {
            get {
                return ((byte)(this["setSectionColorB"]));
            }
            set {
                this["setSectionColorB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setIsWorkSwitchActiveLow {
            get {
                return ((bool)(this["setIsWorkSwitchActiveLow"]));
            }
            set {
                this["setIsWorkSwitchActiveLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIsWorkSwitchEnabled {
            get {
                return ((bool)(this["setIsWorkSwitchEnabled"]));
            }
            set {
                this["setIsWorkSwitchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string setVehicle_Name {
            get {
                return ((string)(this["setVehicle_Name"]));
            }
            set {
                this["setVehicle_Name"] = value;
            }
        }
    }
}
