//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgOpenGPS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-32")]
        public double setDisplay_camPitch {
            get {
                return ((double)(this["setDisplay_camPitch"]));
            }
            set {
                this["setDisplay_camPitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM GPS...")]
        public string setPort_portNameGPS {
            get {
                return ((string)(this["setPort_portNameGPS"]));
            }
            set {
                this["setPort_portNameGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38400")]
        public int setPort_baudRate {
            get {
                return ((int)(this["setPort_baudRate"]));
            }
            set {
                this["setPort_baudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 30")]
        public global::System.Drawing.Point setWindow_Location {
            get {
                return ((global::System.Drawing.Point)(this["setWindow_Location"]));
            }
            set {
                this["setWindow_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024, 768")]
        public global::System.Drawing.Size setWindow_Size {
            get {
                return ((global::System.Drawing.Size)(this["setWindow_Size"]));
            }
            set {
                this["setWindow_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWindow_Maximized {
            get {
                return ((bool)(this["setWindow_Maximized"]));
            }
            set {
                this["setWindow_Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setWindow_Minimized {
            get {
                return ((bool)(this["setWindow_Minimized"]));
            }
            set {
                this["setWindow_Minimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM Section...")]
        public string setPort_portNameRelay {
            get {
                return ((string)(this["setPort_portNameRelay"]));
            }
            set {
                this["setPort_portNameRelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasRelayConnected {
            get {
                return ((bool)(this["setPort_wasRelayConnected"]));
            }
            set {
                this["setPort_wasRelayConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setDisplay_triangleResolution {
            get {
                return ((double)(this["setDisplay_triangleResolution"]));
            }
            set {
                this["setDisplay_triangleResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isMetric {
            get {
                return ((bool)(this["setMenu_isMetric"]));
            }
            set {
                this["setMenu_isMetric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isGridOn {
            get {
                return ((bool)(this["setMenu_isGridOn"]));
            }
            set {
                this["setMenu_isGridOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isLightbarOn {
            get {
                return ((bool)(this["setMenu_isLightbarOn"]));
            }
            set {
                this["setMenu_isLightbarOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setF_CurrentDir {
            get {
                return ((string)(this["setF_CurrentDir"]));
            }
            set {
                this["setF_CurrentDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setF_IsWorkSwitchActiveLow {
            get {
                return ((bool)(this["setF_IsWorkSwitchActiveLow"]));
            }
            set {
                this["setF_IsWorkSwitchActiveLow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setF_IsWorkSwitchEnabled {
            get {
                return ((bool)(this["setF_IsWorkSwitchEnabled"]));
            }
            set {
                this["setF_IsWorkSwitchEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM AS")]
        public string setPort_portNameAutoSteer {
            get {
                return ((string)(this["setPort_portNameAutoSteer"]));
            }
            set {
                this["setPort_portNameAutoSteer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setPort_wasAutoSteerConnected {
            get {
                return ((bool)(this["setPort_wasAutoSteerConnected"]));
            }
            set {
                this["setPort_wasAutoSteerConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setIMU_pitchZeroX16 {
            get {
                return ((int)(this["setIMU_pitchZeroX16"]));
            }
            set {
                this["setIMU_pitchZeroX16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setIMU_rollZeroX16 {
            get {
                return ((int)(this["setIMU_rollZeroX16"]));
            }
            set {
                this["setIMU_rollZeroX16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isLogNMEA {
            get {
                return ((bool)(this["setMenu_isLogNMEA"]));
            }
            set {
                this["setMenu_isLogNMEA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setF_minFixStep {
            get {
                return ((double)(this["setF_minFixStep"]));
            }
            set {
                this["setF_minFixStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte setAS_Ko {
            get {
                return ((byte)(this["setAS_Ko"]));
            }
            set {
                this["setAS_Ko"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte setAS_Kp {
            get {
                return ((byte)(this["setAS_Kp"]));
            }
            set {
                this["setAS_Kp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setAS_Ki {
            get {
                return ((byte)(this["setAS_Ki"]));
            }
            set {
                this["setAS_Ki"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte setAS_Kd {
            get {
                return ((byte)(this["setAS_Kd"]));
            }
            set {
                this["setAS_Kd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127")]
        public byte setAS_steerAngleOffset {
            get {
                return ((byte)(this["setAS_steerAngleOffset"]));
            }
            set {
                this["setAS_steerAngleOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setF_UserTripAlarm {
            get {
                return ((double)(this["setF_UserTripAlarm"]));
            }
            set {
                this["setF_UserTripAlarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setF_UserTotalArea {
            get {
                return ((double)(this["setF_UserTotalArea"]));
            }
            set {
                this["setF_UserTotalArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public byte setAS_minSteerPWM {
            get {
                return ((byte)(this["setAS_minSteerPWM"]));
            }
            set {
                this["setAS_minSteerPWM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setF_boundaryTriggerDistance {
            get {
                return ((double)(this["setF_boundaryTriggerDistance"]));
            }
            set {
                this["setF_boundaryTriggerDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public byte setAS_maxIntegral {
            get {
                return ((byte)(this["setAS_maxIntegral"]));
            }
            set {
                this["setAS_maxIntegral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isSideGuideLines {
            get {
                return ((bool)(this["setMenu_isSideGuideLines"]));
            }
            set {
                this["setMenu_isSideGuideLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public byte setAS_countsPerDegree {
            get {
                return ((byte)(this["setAS_countsPerDegree"]));
            }
            set {
                this["setAS_countsPerDegree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isPureOn {
            get {
                return ((bool)(this["setMenu_isPureOn"]));
            }
            set {
                this["setMenu_isPureOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keyhole.txt")]
        public string setAS_youTurnShape {
            get {
                return ((string)(this["setAS_youTurnShape"]));
            }
            set {
                this["setAS_youTurnShape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int setIP_thisPort {
            get {
                return ((int)(this["setIP_thisPort"]));
            }
            set {
                this["setIP_thisPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.255")]
        public string setIP_autoSteerIP {
            get {
                return ((string)(this["setIP_autoSteerIP"]));
            }
            set {
                this["setIP_autoSteerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8888")]
        public int setIP_autoSteerPort {
            get {
                return ((int)(this["setIP_autoSteerPort"]));
            }
            set {
                this["setIP_autoSteerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.255")]
        public string setIP_rateRelayIP {
            get {
                return ((string)(this["setIP_rateRelayIP"]));
            }
            set {
                this["setIP_rateRelayIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7777")]
        public int setIP_rateRelayPort {
            get {
                return ((int)(this["setIP_rateRelayPort"]));
            }
            set {
                this["setIP_rateRelayPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isSimulatorOn {
            get {
                return ((bool)(this["setMenu_isSimulatorOn"]));
            }
            set {
                this["setMenu_isSimulatorOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMenu_isSkyOn {
            get {
                return ((bool)(this["setMenu_isSkyOn"]));
            }
            set {
                this["setMenu_isSkyOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string setF_culture {
            get {
                return ((string)(this["setF_culture"]));
            }
            set {
                this["setF_culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string setF_workingDirectory {
            get {
                return ((string)(this["setF_workingDirectory"]));
            }
            set {
                this["setF_workingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68wESU")]
        public string setIMU_UID {
            get {
                return ((string)(this["setIMU_UID"]));
            }
            set {
                this["setIMU_UID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isRollFromAutoSteer {
            get {
                return ((bool)(this["setIMU_isRollFromAutoSteer"]));
            }
            set {
                this["setIMU_isRollFromAutoSteer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isHeadingFromBrick {
            get {
                return ((bool)(this["setIMU_isHeadingFromBrick"]));
            }
            set {
                this["setIMU_isHeadingFromBrick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isHeadingFromAutoSteer {
            get {
                return ((bool)(this["setIMU_isHeadingFromAutoSteer"]));
            }
            set {
                this["setIMU_isHeadingFromAutoSteer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isRollFromBrick {
            get {
                return ((bool)(this["setIMU_isRollFromBrick"]));
            }
            set {
                this["setIMU_isRollFromBrick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int setPort_NMEAHz {
            get {
                return ((int)(this["setPort_NMEAHz"]));
            }
            set {
                this["setPort_NMEAHz"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isHeadingFromPAOGI {
            get {
                return ((bool)(this["setIMU_isHeadingFromPAOGI"]));
            }
            set {
                this["setIMU_isHeadingFromPAOGI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isRollFromGPS {
            get {
                return ((bool)(this["setIMU_isRollFromGPS"]));
            }
            set {
                this["setIMU_isRollFromGPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int setDisplay_lightbarCmPerPixel {
            get {
                return ((int)(this["setDisplay_lightbarCmPerPixel"]));
            }
            set {
                this["setDisplay_lightbarCmPerPixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setUDP_isOn {
            get {
                return ((bool)(this["setUDP_isOn"]));
            }
            set {
                this["setUDP_isOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GGA")]
        public string setGPS_fixFromWhichSentence {
            get {
                return ((string)(this["setGPS_fixFromWhichSentence"]));
            }
            set {
                this["setGPS_fixFromWhichSentence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fix")]
        public string setGPS_headingFromWhichSource {
            get {
                return ((string)(this["setGPS_headingFromWhichSource"]));
            }
            set {
                this["setGPS_headingFromWhichSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53.4360564")]
        public double setGPS_SimLatitude {
            get {
                return ((double)(this["setGPS_SimLatitude"]));
            }
            set {
                this["setGPS_SimLatitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-111.160047")]
        public double setGPS_SimLongitude {
            get {
                return ((double)(this["setGPS_SimLongitude"]));
            }
            set {
                this["setGPS_SimLongitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("69.75.31.235")]
        public string setNTRIP_casterIP {
            get {
                return ((string)(this["setNTRIP_casterIP"]));
            }
            set {
                this["setNTRIP_casterIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2101")]
        public int setNTRIP_casterPort {
            get {
                return ((int)(this["setNTRIP_casterPort"]));
            }
            set {
                this["setNTRIP_casterPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AZU1")]
        public string setNTRIP_mount {
            get {
                return ((string)(this["setNTRIP_mount"]));
            }
            set {
                this["setNTRIP_mount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setNTRIP_userName {
            get {
                return ((string)(this["setNTRIP_userName"]));
            }
            set {
                this["setNTRIP_userName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setNTRIP_userPassword {
            get {
                return ((string)(this["setNTRIP_userPassword"]));
            }
            set {
                this["setNTRIP_userPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isOn {
            get {
                return ((bool)(this["setNTRIP_isOn"]));
            }
            set {
                this["setNTRIP_isOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int setNTRIP_sendGGAInterval {
            get {
                return ((int)(this["setNTRIP_sendGGAInterval"]));
            }
            set {
                this["setNTRIP_sendGGAInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setNTRIP_sendToUDPPort {
            get {
                return ((int)(this["setNTRIP_sendToUDPPort"]));
            }
            set {
                this["setNTRIP_sendToUDPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53")]
        public double setNTRIP_manualLat {
            get {
                return ((double)(this["setNTRIP_manualLat"]));
            }
            set {
                this["setNTRIP_manualLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-111")]
        public double setNTRIP_manualLon {
            get {
                return ((double)(this["setNTRIP_manualLon"]));
            }
            set {
                this["setNTRIP_manualLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.rtk2go.com")]
        public string setNTRIP_casterURL {
            get {
                return ((string)(this["setNTRIP_casterURL"]));
            }
            set {
                this["setNTRIP_casterURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setNTRIP_isGGAManual {
            get {
                return ((bool)(this["setNTRIP_isGGAManual"]));
            }
            set {
                this["setNTRIP_isGGAManual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int setAS_snapDistance {
            get {
                return ((int)(this["setAS_snapDistance"]));
            }
            set {
                this["setAS_snapDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setF_IsWorkSwitchManual {
            get {
                return ((bool)(this["setF_IsWorkSwitchManual"]));
            }
            set {
                this["setF_IsWorkSwitchManual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setDistance_TreeSpacing {
            get {
                return ((double)(this["setDistance_TreeSpacing"]));
            }
            set {
                this["setDistance_TreeSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isHeadingFromExtUDP {
            get {
                return ((bool)(this["setIMU_isHeadingFromExtUDP"]));
            }
            set {
                this["setIMU_isHeadingFromExtUDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setIMU_isRollFromExtUDP {
            get {
                return ((bool)(this["setIMU_isRollFromExtUDP"]));
            }
            set {
                this["setIMU_isRollFromExtUDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setAS_isAutoSteerAutoOn {
            get {
                return ((bool)(this["setAS_isAutoSteerAutoOn"]));
            }
            set {
                this["setAS_isAutoSteerAutoOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDisplay_isBatmanOn {
            get {
                return ((bool)(this["setDisplay_isBatmanOn"]));
            }
            set {
                this["setDisplay_isBatmanOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setAS_isJRK {
            get {
                return ((bool)(this["setAS_isJRK"]));
            }
            set {
                this["setAS_isJRK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int setDisplay_lineWidth {
            get {
                return ((int)(this["setDisplay_lineWidth"]));
            }
            set {
                this["setDisplay_lineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("97, 600")]
        public global::System.Drawing.Point setDisplay_panelSimLocation {
            get {
                return ((global::System.Drawing.Point)(this["setDisplay_panelSimLocation"]));
            }
            set {
                this["setDisplay_panelSimLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double setTram_eqWidth {
            get {
                return ((double)(this["setTram_eqWidth"]));
            }
            set {
                this["setTram_eqWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.7")]
        public double setTram_wheelSpacing {
            get {
                return ((double)(this["setTram_wheelSpacing"]));
            }
            set {
                this["setTram_wheelSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double setTram_snapAdj {
            get {
                return ((double)(this["setTram_snapAdj"]));
            }
            set {
                this["setTram_snapAdj"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setTram_passes {
            get {
                return ((int)(this["setTram_passes"]));
            }
            set {
                this["setTram_passes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setTram_offset {
            get {
                return ((double)(this["setTram_offset"]));
            }
            set {
                this["setTram_offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int setMenu_isOGLZoomOn {
            get {
                return ((int)(this["setMenu_isOGLZoomOn"]));
            }
            set {
                this["setMenu_isOGLZoomOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isUTurnAlwaysOn {
            get {
                return ((bool)(this["setMenu_isUTurnAlwaysOn"]));
            }
            set {
                this["setMenu_isUTurnAlwaysOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isCompassOn {
            get {
                return ((bool)(this["setMenu_isCompassOn"]));
            }
            set {
                this["setMenu_isCompassOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setMenu_isSpeedoOn {
            get {
                return ((bool)(this["setMenu_isSpeedoOn"]));
            }
            set {
                this["setMenu_isSpeedoOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setNTRIP_isTCP {
            get {
                return ((bool)(this["setNTRIP_isTCP"]));
            }
            set {
                this["setNTRIP_isTCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("210, 220, 230")]
        public global::System.Drawing.Color setDisplay_colorDayMode {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorDayMode"]));
            }
            set {
                this["setDisplay_colorDayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 60, 60")]
        public global::System.Drawing.Color setDisplay_colorNightMode {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorNightMode"]));
            }
            set {
                this["setDisplay_colorNightMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27, 151, 160")]
        public global::System.Drawing.Color setDisplay_colorSectionsDay {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorSectionsDay"]));
            }
            set {
                this["setDisplay_colorSectionsDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 90, 90")]
        public global::System.Drawing.Color setDisplay_colorFieldDay {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorFieldDay"]));
            }
            set {
                this["setDisplay_colorFieldDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDisplay_isSimple {
            get {
                return ((bool)(this["setDisplay_isSimple"]));
            }
            set {
                this["setDisplay_isSimple"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDisplay_isDayMode {
            get {
                return ((bool)(this["setDisplay_isDayMode"]));
            }
            set {
                this["setDisplay_isDayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27, 100, 100")]
        public global::System.Drawing.Color setDisplay_colorSectionsNight {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorSectionsNight"]));
            }
            set {
                this["setDisplay_colorSectionsNight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 60, 60")]
        public global::System.Drawing.Color setDisplay_colorFieldNight {
            get {
                return ((global::System.Drawing.Color)(this["setDisplay_colorFieldNight"]));
            }
            set {
                this["setDisplay_colorFieldNight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDisplay_isAutoDayNight {
            get {
                return ((bool)(this["setDisplay_isAutoDayNight"]));
            }
            set {
                this["setDisplay_isAutoDayNight"] = value;
            }
        }
    }
}
