//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgOpenGPS.Classes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class gStr_Empty {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal gStr_Empty() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgOpenGPS.Classes.gStr.Empty", typeof(gStr_Empty).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsABCurve {
            get {
                return ResourceManager.GetString("gsABCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsABline {
            get {
                return ResourceManager.GetString("gsABline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsAbout {
            get {
                return ResourceManager.GetString("gsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsActionHasBeenCancelled {
            get {
                return ResourceManager.GetString("gsActionHasBeenCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsActual {
            get {
                return ResourceManager.GetString("gsActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsAgressiveness {
            get {
                return ResourceManager.GetString("gsAgressiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsArea {
            get {
                return ResourceManager.GetString("gsArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsAreYouSure {
            get {
                return ResourceManager.GetString("gsAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsAutoSteerConfiguration {
            get {
                return ResourceManager.GetString("gsAutoSteerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsBasedOnField {
            get {
                return ResourceManager.GetString("gsBasedOnField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsBoundary {
            get {
                return ResourceManager.GetString("gsBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsChooseADifferentField {
            get {
                return ResourceManager.GetString("gsChooseADifferentField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsChooseADifferentName {
            get {
                return ResourceManager.GetString("gsChooseADifferentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsChooseBuildDifferentone {
            get {
                return ResourceManager.GetString("gsChooseBuildDifferentone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsCloseFieldFirst {
            get {
                return ResourceManager.GetString("gsCloseFieldFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsColors {
            get {
                return ResourceManager.GetString("gsColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsCompletelyDeleteBoundary {
            get {
                return ResourceManager.GetString("gsCompletelyDeleteBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsCreateNewField {
            get {
                return ResourceManager.GetString("gsCreateNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsDeleteAppliedArea {
            get {
                return ResourceManager.GetString("gsDeleteAppliedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsDeleteContourPaths {
            get {
                return ResourceManager.GetString("gsDeleteContourPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsDeleteForSure {
            get {
                return ResourceManager.GetString("gsDeleteForSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsDirectories {
            get {
                return ResourceManager.GetString("gsDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsDirectoryExists {
            get {
                return ResourceManager.GetString("gsDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsDriveThru {
            get {
                return ResourceManager.GetString("gsDriveThru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsDriving {
            get {
                return ResourceManager.GetString("gsDriving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsEast {
            get {
                return ResourceManager.GetString("gsEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsEditABCurve {
            get {
                return ResourceManager.GetString("gsEditABCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsEditABLine {
            get {
                return ResourceManager.GetString("gsEditABLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsEnterCoordinatesForSimulator {
            get {
                return ResourceManager.GetString("gsEnterCoordinatesForSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsEnterFieldName {
            get {
                return ResourceManager.GetString("gsEnterFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsEnterSimCoords {
            get {
                return ResourceManager.GetString("gsEnterSimCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsError {
            get {
                return ResourceManager.GetString("gsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsErrorreadingKML {
            get {
                return ResourceManager.GetString("gsErrorreadingKML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsFieldFileIsCorrupt {
            get {
                return ResourceManager.GetString("gsFieldFileIsCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsFieldIsOpen {
            get {
                return ResourceManager.GetString("gsFieldIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsFieldNotOpen {
            get {
                return ResourceManager.GetString("gsFieldNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsFileError {
            get {
                return ResourceManager.GetString("gsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsHeadland {
            get {
                return ResourceManager.GetString("gsHeadland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsHeadlandForm {
            get {
                return ResourceManager.GetString("gsHeadlandForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsInches {
            get {
                return ResourceManager.GetString("gsInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsInner {
            get {
                return ResourceManager.GetString("gsInner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsKMH {
            get {
                return ResourceManager.GetString("gsKMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsLanguage {
            get {
                return ResourceManager.GetString("gsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsMakeBoundaryContours {
            get {
                return ResourceManager.GetString("gsMakeBoundaryContours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsMeters {
            get {
                return ResourceManager.GetString("gsMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsMPH {
            get {
                return ResourceManager.GetString("gsMPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsNew {
            get {
                return ResourceManager.GetString("gsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsNone {
            get {
                return ResourceManager.GetString("gsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsNoneUsed {
            get {
                return ResourceManager.GetString("gsNoneUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsNorth {
            get {
                return ResourceManager.GetString("gsNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsNothingDeleted {
            get {
                return ResourceManager.GetString("gsNothingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsOffset {
            get {
                return ResourceManager.GetString("gsOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsOffsetFix {
            get {
                return ResourceManager.GetString("gsOffsetFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsOuter {
            get {
                return ResourceManager.GetString("gsOuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsOvershootReduction {
            get {
                return ResourceManager.GetString("gsOvershootReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsPass {
            get {
                return ResourceManager.GetString("gsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsPasses {
            get {
                return ResourceManager.GetString("gsPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsPause {
            get {
                return ResourceManager.GetString("gsPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsRecord {
            get {
                return ResourceManager.GetString("gsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsResetAll {
            get {
                return ResourceManager.GetString("gsResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsResetAllForSure {
            get {
                return ResourceManager.GetString("gsResetAllForSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsResume {
            get {
                return ResourceManager.GetString("gsResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsSaveAndReturn {
            get {
                return ResourceManager.GetString("gsSaveAndReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsSetPoint {
            get {
                return ResourceManager.GetString("gsSetPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsShiftGPSPosition {
            get {
                return ResourceManager.GetString("gsShiftGPSPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsSimulatorOn {
            get {
                return ResourceManager.GetString("gsSimulatorOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsSmoothABCurve {
            get {
                return ResourceManager.GetString("gsSmoothABCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsSort {
            get {
                return ResourceManager.GetString("gsSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsSouth {
            get {
                return ResourceManager.GetString("gsSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsSpacing {
            get {
                return ResourceManager.GetString("gsSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsStartDeleteABoundary {
            get {
                return ResourceManager.GetString("gsStartDeleteABoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsStartNewField {
            get {
                return ResourceManager.GetString("gsStartNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsSteerChart {
            get {
                return ResourceManager.GetString("gsSteerChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsStopRecordPauseBoundary {
            get {
                return ResourceManager.GetString("gsStopRecordPauseBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsToFile {
            get {
                return ResourceManager.GetString("gsToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsTopFieldView {
            get {
                return ResourceManager.GetString("gsTopFieldView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsTramLines {
            get {
                return ResourceManager.GetString("gsTramLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsUseSelected {
            get {
                return ResourceManager.GetString("gsUseSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string gsWebCam {
            get {
                return ResourceManager.GetString("gsWebCam", resourceCulture);
            }
        }
    }
}
